/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tarea9;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author carra
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        TFpassword.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TFdni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFpassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login CCP");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 750));

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        logo.setToolTipText("Logo Empresa");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Bienvenido al Portal de la Empresa");

        TFdni.setForeground(new java.awt.Color(204, 204, 204));
        TFdni.setText("NIF / NIE");
        TFdni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFdniFocusGained(evt);
            }
        });
        TFdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFdniKeyReleased(evt);
            }
        });

        jLabel2.setText("NIF / NIE:");

        TFpassword.setForeground(new java.awt.Color(204, 204, 204));
        TFpassword.setText("********");
        TFpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFpasswordFocusGained(evt);
            }
        });

        jLabel3.setText("Contraseña: ");

        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Error NIF /NIE ");

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Contrsaeña no valida");

        jLabel6.setText("¿Olvido su contraseña?");

        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setText("Pinche Aqui");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jButton1.setText("Iniciar Sesión");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(TFdni, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(TFpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(197, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(logo)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(TFdni, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(TFpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFdniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFdniFocusGained
        if (TFdni.getText().equals("NIF / NIE")) {
            TFdni.setText("");
            TFdni.setForeground(Color.BLACK);
        }
        if (String.valueOf(TFpassword.getPassword()).isEmpty()) {
            TFpassword.setText("********");
            TFpassword.setForeground(Color.gray);
        }

    }//GEN-LAST:event_TFdniFocusGained

    private void TFpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFpasswordFocusGained
        if (String.valueOf(TFpassword.getPassword()).equals("********")) {
            TFpassword.setText("");
            TFpassword.setForeground(Color.black);
        }
        if (TFdni.getText().isEmpty()) {
            TFdni.setText("NIF / NIE");
            TFdni.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TFpasswordFocusGained

    private void TFdniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFdniKeyReleased
        // TODO add your handling code here:
        if (!comprobarDNI(TFdni.getText())) {
            jLabel4.setVisible(true);
            TFpassword.setEnabled(false);
        } else {
            jLabel4.setVisible(false);
            TFpassword.setEnabled(true);
        }
    }//GEN-LAST:event_TFdniKeyReleased

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if (!comprobarDNI(TFdni.getText())) {
            jLabel4.setVisible(true);
        } else {
            jLabel4.setVisible(false);

            if (String.valueOf(TFpassword.getPassword()).isBlank() || String.valueOf(TFpassword.getPassword()).equals("********")) {
                jLabel5.setVisible(true);

            } else {
                jLabel5.setVisible(false);
                JOptionPane jop = new JOptionPane("Login Realizado con Extio", JOptionPane.INFORMATION_MESSAGE);
                javax.swing.JDialog jd = jop.createDialog("INFO");
                jd.setLocationRelativeTo(this);
                jd.setVisible(true);
                jd.setAlwaysOnTop(true);
            }
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
          try {
            Desktop.getDesktop().browse(new URI("https://www.iesaglinares.com/"));
        } catch (IOException ex) {
            //System.err.println("Ha ocurrido una IOException");
        } catch (URISyntaxException ex) {
            //System.err.println("No ha encontrado la URL");
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    public static boolean comprobarDNI(String DNI) {
        String DNI2 = DNI.toUpperCase();

        HashMap<Integer, String> mapa = generarHashMap();

        if (DNI2.matches("[0-9]{8}[A-Z]")) {
            if (DNI2.substring(8).equals(mapa.get(Integer.parseInt(DNI2.substring(0, 8)) % 23))) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }

    }

    private static HashMap<Integer, String> generarHashMap() {
        HashMap<Integer, String> mapa = new HashMap();
        mapa.put(0, "T");
        mapa.put(1, "R");
        mapa.put(2, "W");
        mapa.put(3, "A");
        mapa.put(4, "G");
        mapa.put(5, "M");
        mapa.put(6, "Y");
        mapa.put(7, "F");
        mapa.put(8, "P");
        mapa.put(9, "D");
        mapa.put(10, "X");
        mapa.put(11, "B");
        mapa.put(12, "N");
        mapa.put(13, "J");
        mapa.put(14, "Z");
        mapa.put(15, "S");
        mapa.put(16, "Q");
        mapa.put(17, "V");
        mapa.put(18, "H");
        mapa.put(19, "L");
        mapa.put(20, "C");
        mapa.put(21, "K");
        mapa.put(22, "E");
        return mapa;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFdni;
    private javax.swing.JPasswordField TFpassword;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
