-- MySQL Script generated by MySQL Workbench
-- Mon Dec  5 19:18:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Prueba
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Prueba` ;

-- -----------------------------------------------------
-- Schema Prueba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Prueba` ;
USE `Prueba` ;

-- -----------------------------------------------------
-- Table `Prueba`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Prueba`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `Prueba`.`CLIENTE` (
  `DNI` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellidos` VARCHAR(60) NOT NULL,
  `fechaNac` DATE NOT NULL,
  `telefono` INT NOT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prueba`.`PROVEEDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Prueba`.`PROVEEDOR` ;

CREATE TABLE IF NOT EXISTS `Prueba`.`PROVEEDOR` (
  `NIF` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`NIF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prueba`.`PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Prueba`.`PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `Prueba`.`PRODUCTO` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  `PROVEEDOR_NIF` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_PRODUCTO_PROVEEDOR1_idx` (`PROVEEDOR_NIF` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDOR_NIF`)
    REFERENCES `Prueba`.`PROVEEDOR` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prueba`.`CLIENTE_has_PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Prueba`.`CLIENTE_has_PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `Prueba`.`CLIENTE_has_PRODUCTO` (
  `CLIENTE_DNI` INT NOT NULL,
  `PRODUCTO_codigo` INT NOT NULL,
  PRIMARY KEY (`CLIENTE_DNI`, `PRODUCTO_codigo`),
  INDEX `fk_CLIENTE_has_PRODUCTO_PRODUCTO1_idx` (`PRODUCTO_codigo` ASC) VISIBLE,
  INDEX `fk_CLIENTE_has_PRODUCTO_CLIENTE1_idx` (`CLIENTE_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_has_PRODUCTO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_DNI`)
    REFERENCES `Prueba`.`CLIENTE` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_has_PRODUCTO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_codigo`)
    REFERENCES `Prueba`.`PRODUCTO` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
